POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRpbGxpIiwiaWQiOiI2MjM3ODcyNGIwZWVmODJkMTQ3MmFmMjEiLCJpYXQiOjE2NDg2NDM2OTJ9.B9dbJ2PR_D1r8sM5z_49iwhhtDdYG9a8beIsuYZUbL4

{
    "title": "Toto tuo, veto vie",
    "author": "Heppa Hertta",
    "url": "www.fullstack.com"
}