PUT http://localhost:3003/api/blogs/62348ac6dc9e38be69e9421d
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRpbGxpIiwiaWQiOiI2MjM3ODcyNGIwZWVmODJkMTQ3MmFmMjEiLCJpYXQiOjE2NDg3MjcxMzJ9.rCu2WNp_ALMbc-1CFsSazvk1_dlJu34HBO26POTAjdE

{
    "title": "Tilanne joka selitykselle",
    "author": "Pentti Siimes",
    "url": "www.selitysjokatilanteelle.com",
    "likes": 7
}