PUT http://localhost:3003/api/blogs/6218cbc4fbcb8c1bf55779c3
Content-Type: application/json

{
    "title": "Tilanne joka selitykselle",
    "author": "Pentti Siimes",
    "url": "www.selitysjokatilanteelle.com",
    "likes": "Sikailija Sid"
}